# Generated by Django 2.2.5 on 2019-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tag Name')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
            ],
            options={
                'verbose_name_plural': "Brandon's Tag",
                'db_table': 'brandon_tag',
            },
        ),
    ]
