# Generated by Django 2.2.6 on 2019-10-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('bkuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Registerd')),
                ('bkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bkuser.Bkuser', verbose_name='User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'BK Order',
                'verbose_name_plural': 'BK Order',
                'db_table': 'bk_order',
            },
        ),
    ]
