# Generated by Django 2.2.6 on 2019-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Product_Name')),
                ('price', models.IntegerField(verbose_name='Product_Price')),
                ('description', models.TextField(verbose_name='Product_Description')),
                ('stock', models.IntegerField(verbose_name='Product_Stock')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name': 'BK Product',
                'verbose_name_plural': 'BK Product',
                'db_table': 'bk_product',
            },
        ),
    ]
