# Generated by Django 2.2.5 on 2019-09-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bkuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('contents', models.TextField(verbose_name='Content')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bkuser.Bkuser', verbose_name='Writer')),
            ],
            options={
                'verbose_name_plural': "Brandon's Board",
                'db_table': 'brandon_content',
            },
        ),
    ]
