# Generated by Django 2.2.6 on 2019-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bkuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
            ],
            options={
                'verbose_name': 'BK User',
                'verbose_name_plural': 'BK User',
                'db_table': 'bk_user',
            },
        ),
    ]
